// brainfuck_helpers.c
// Written in 2019 by Dmytro Meleshko <dmytro.meleshko@gmail.com>
// To the extent possible under law, the author(s) have dedicated all copyright
// and related and neighboring rights to this software to the public domain
// worldwide. This software is distributed without any warranty. You should have
// received a copy of the CC0 Public Domain Dedication along with this software.
// If not, see <http://creativecommons.org/publicdomain/zero/1.0/>.

extern void command_nop(void);
extern void command_move_left(void);
extern void command_move_right(void);
extern void command_increment(void);
extern void command_decrement(void);
extern void command_print(void);
extern void command_read(void);
extern void command_loop_begin(void);
extern void command_loop_end(void);

void *command_handlers_table[] = {
    command_nop,        // 00
    command_nop,        // 01
    command_nop,        // 02
    command_nop,        // 03
    command_nop,        // 04
    command_nop,        // 05
    command_nop,        // 06
    command_nop,        // 07
    command_nop,        // 08
    command_nop,        // 09
    command_nop,        // 0A
    command_nop,        // 0B
    command_nop,        // 0C
    command_nop,        // 0D
    command_nop,        // 0E
    command_nop,        // 0F
    command_nop,        // 10
    command_nop,        // 11
    command_nop,        // 12
    command_nop,        // 13
    command_nop,        // 14
    command_nop,        // 15
    command_nop,        // 16
    command_nop,        // 17
    command_nop,        // 18
    command_nop,        // 19
    command_nop,        // 1A
    command_nop,        // 1B
    command_nop,        // 1C
    command_nop,        // 1D
    command_nop,        // 1E
    command_nop,        // 1F
    command_nop,        // 20
    command_nop,        // 21
    command_nop,        // 22
    command_nop,        // 23
    command_nop,        // 24
    command_nop,        // 25
    command_nop,        // 26
    command_nop,        // 27
    command_nop,        // 28
    command_nop,        // 29
    command_nop,        // 2A
    command_increment,  // 2B
    command_read,       // 2C
    command_decrement,  // 2D
    command_print,      // 2E
    command_nop,        // 2F
    command_nop,        // 30
    command_nop,        // 31
    command_nop,        // 32
    command_nop,        // 33
    command_nop,        // 34
    command_nop,        // 35
    command_nop,        // 36
    command_nop,        // 37
    command_nop,        // 38
    command_nop,        // 39
    command_nop,        // 3A
    command_nop,        // 3B
    command_move_left,  // 3C
    command_nop,        // 3D
    command_move_right, // 3E
    command_nop,        // 3F
    command_nop,        // 40
    command_nop,        // 41
    command_nop,        // 42
    command_nop,        // 43
    command_nop,        // 44
    command_nop,        // 45
    command_nop,        // 46
    command_nop,        // 47
    command_nop,        // 48
    command_nop,        // 49
    command_nop,        // 4A
    command_nop,        // 4B
    command_nop,        // 4C
    command_nop,        // 4D
    command_nop,        // 4E
    command_nop,        // 4F
    command_nop,        // 50
    command_nop,        // 51
    command_nop,        // 52
    command_nop,        // 53
    command_nop,        // 54
    command_nop,        // 55
    command_nop,        // 56
    command_nop,        // 57
    command_nop,        // 58
    command_nop,        // 59
    command_nop,        // 5A
    command_loop_begin, // 5B
    command_nop,        // 5C
    command_loop_end,   // 5D
    command_nop,        // 5E
    command_nop,        // 5F
    command_nop,        // 60
    command_nop,        // 61
    command_nop,        // 62
    command_nop,        // 63
    command_nop,        // 64
    command_nop,        // 65
    command_nop,        // 66
    command_nop,        // 67
    command_nop,        // 68
    command_nop,        // 69
    command_nop,        // 6A
    command_nop,        // 6B
    command_nop,        // 6C
    command_nop,        // 6D
    command_nop,        // 6E
    command_nop,        // 6F
    command_nop,        // 70
    command_nop,        // 71
    command_nop,        // 72
    command_nop,        // 73
    command_nop,        // 74
    command_nop,        // 75
    command_nop,        // 76
    command_nop,        // 77
    command_nop,        // 78
    command_nop,        // 79
    command_nop,        // 7A
    command_nop,        // 7B
    command_nop,        // 7C
    command_nop,        // 7D
    command_nop,        // 7E
    command_nop,        // 7F
    command_nop,        // 80
    command_nop,        // 81
    command_nop,        // 82
    command_nop,        // 83
    command_nop,        // 84
    command_nop,        // 85
    command_nop,        // 86
    command_nop,        // 87
    command_nop,        // 88
    command_nop,        // 89
    command_nop,        // 8A
    command_nop,        // 8B
    command_nop,        // 8C
    command_nop,        // 8D
    command_nop,        // 8E
    command_nop,        // 8F
    command_nop,        // 90
    command_nop,        // 91
    command_nop,        // 92
    command_nop,        // 93
    command_nop,        // 94
    command_nop,        // 95
    command_nop,        // 96
    command_nop,        // 97
    command_nop,        // 98
    command_nop,        // 99
    command_nop,        // 9A
    command_nop,        // 9B
    command_nop,        // 9C
    command_nop,        // 9D
    command_nop,        // 9E
    command_nop,        // 9F
    command_nop,        // A0
    command_nop,        // A1
    command_nop,        // A2
    command_nop,        // A3
    command_nop,        // A4
    command_nop,        // A5
    command_nop,        // A6
    command_nop,        // A7
    command_nop,        // A8
    command_nop,        // A9
    command_nop,        // AA
    command_nop,        // AB
    command_nop,        // AC
    command_nop,        // AD
    command_nop,        // AE
    command_nop,        // AF
    command_nop,        // B0
    command_nop,        // B1
    command_nop,        // B2
    command_nop,        // B3
    command_nop,        // B4
    command_nop,        // B5
    command_nop,        // B6
    command_nop,        // B7
    command_nop,        // B8
    command_nop,        // B9
    command_nop,        // BA
    command_nop,        // BB
    command_nop,        // BC
    command_nop,        // BD
    command_nop,        // BE
    command_nop,        // BF
    command_nop,        // C0
    command_nop,        // C1
    command_nop,        // C2
    command_nop,        // C3
    command_nop,        // C4
    command_nop,        // C5
    command_nop,        // C6
    command_nop,        // C7
    command_nop,        // C8
    command_nop,        // C9
    command_nop,        // CA
    command_nop,        // CB
    command_nop,        // CC
    command_nop,        // CD
    command_nop,        // CE
    command_nop,        // CF
    command_nop,        // D0
    command_nop,        // D1
    command_nop,        // D2
    command_nop,        // D3
    command_nop,        // D4
    command_nop,        // D5
    command_nop,        // D6
    command_nop,        // D7
    command_nop,        // D8
    command_nop,        // D9
    command_nop,        // DA
    command_nop,        // DB
    command_nop,        // DC
    command_nop,        // DD
    command_nop,        // DE
    command_nop,        // DF
    command_nop,        // E0
    command_nop,        // E1
    command_nop,        // E2
    command_nop,        // E3
    command_nop,        // E4
    command_nop,        // E5
    command_nop,        // E6
    command_nop,        // E7
    command_nop,        // E8
    command_nop,        // E9
    command_nop,        // EA
    command_nop,        // EB
    command_nop,        // EC
    command_nop,        // ED
    command_nop,        // EE
    command_nop,        // EF
    command_nop,        // F0
    command_nop,        // F1
    command_nop,        // F2
    command_nop,        // F3
    command_nop,        // F4
    command_nop,        // F5
    command_nop,        // F6
    command_nop,        // F7
    command_nop,        // F8
    command_nop,        // F9
    command_nop,        // FA
    command_nop,        // FB
    command_nop,        // FC
    command_nop,        // FD
    command_nop,        // FE
    command_nop,        // FF
};
